<a href="https://colab.research.google.com/github/hernansalinas/CursoMetodosComputacionales/blob/main/Material_sesiones/TheGameOfLife.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# El juego de la vida

Se trata de un juego de cero jugadores, lo que quiere decir que su evolución está determinada por el estado inicial y no necesita ninguna entrada de datos posterior. El "tablero de juego" es una malla plana formada por cuadrados (las "células") que se extiende por el infinito en todas las direcciones. Por tanto, cada célula tiene 8 células "vecinas", que son las que están próximas a ella, incluidas las diagonales. Las células tienen dos estados: están "vivas" o "muertas" (o "encendidas" y "apagadas"). El estado de las células evoluciona a lo largo de unidades de tiempo discretas (se podría decir que por turnos). El estado de todas las células se tiene en cuenta para calcular el estado de las mismas al turno siguiente. Todas las células se actualizan simultáneamente en cada turno, siguiendo estas reglas:

- Una célula muerta con exactamente 3 células vecinas vivas "nace" (es decir, al turno siguiente estará viva).

- Una célula viva con 2 o 3 células vecinas vivas sigue viva, en otro caso muere (por "soledad" o "superpoblación").


https://es.wikipedia.org/wiki/Juego_de_la_vida

In [ ]:
import numpy as np
import matplotlib.pylab as plt

In [ ]:
# # Boundary Condition
# def f(k, N):
#   if(k == -1):
#     return N - 1
#   elif (k == N):
#     return 0;
#   else:
#     return k

# def vecinos(i, j, N, c):
#   v = 0
#   for k in range(i - 1, i + 2):
#     for p in range(j - 1, j + 2):
#       ld = c[f(k, N), f(p,N)]
#       v = v + ld
#   return int((v-c[i,j]))

In [ ]:
#===================================================================
def init_(N):
  red = np.zeros( (N + 2, N+2) )
  for i in range(1, N + 1 ):
    for j in range(1, N + 1):
      red[i,j] = int (np.random.randint(2))
  return red

def vecinos(i, j, N, c):
  v = 0
  for k in range(i-1, i+2):
    for p in range(j-1,j+2):
      ld = c[k,p]
      v = v + ld
  return int(v - c[i,j])


In [ ]:
k = 0
f = 0

for i in range(1, N + 1):
  for j in range(1, N + 1):
    v = vecinos(i,j, N, red)
    state = red[i,j]
  #  print(i,j, v)
    if (state == 0.0) : # Si esta muerta
      if (v == 3.0):
      #  print("valor de ", red[i,j])
        red_p[i,j] = 1.0
      else:
        red_p[i,j] = 0.0
    else:      #Si esta viva
      if (v == 2.0 or v == 3.0):
        red_p[i,j] = 1.0
      else :
        red_p[i,j] = 0.0
red_p

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
def evolucion(red, N) :
  red_p = np.zeros( (N + 2, N+2) )
  for i in range(1, N + 1):
    for j in range(1, N + 1):

      v = vecinos(i,j, N, red)
      state = red[i,j]

      if (state == 0.0): #Si esta muerta
        if (v == 3.0):
          red_p[i,j] = 1
        else:
          red_p[i,j] = 0
      else:      #Si esta viva
        if (v == 2.0 or v == 3.0):
          red_p[i,j] = 1
        else:
          red_p[i,j] = 0
  return red_p


In [ ]:
red = init_(N=10)

q1 = evolucion(red,10)

In [ ]:
red

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0.],
       [0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0.],
       [0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
q1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
q2 = evolucion(q1,10)

In [ ]:
q2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
from matplotlib import animation, rc
rc('animation', html='html5')

In [ ]:
def update(i):
  ax.clear()
  ax.imshow(conf[i], cmap="gray")
  ax.axis("off")
  return ax

In [ ]:
def game(N, t):
  red = init_(N)
  conf = np.zeros((t,N+2,N+2))

  for t in range(0, t):
    red_ = evolucion(red, N)
    red = red_
    conf[t]=red
  return conf

In [ ]:
conf = game(30, 100)

In [ ]:
fig = plt.figure(figsize=(5,5))
ax=plt.subplot(1,1,1)
anim = animation.FuncAnimation(fig, update, frames = len(conf), interval = 200)
plt.close()

In [ ]:
anim